name: GoReleaser
on:
  pull_request:
    paths: [ '.goreleaser.yaml' ]

jobs:
  check:
    name: Check Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.19.x"
      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: check
